### ISSUE TITLE
После полной перезагрузки сервера система не может подключиться к БД

### ISSUE THREAD

**Issue by Nord1cWarr1or** [ufame/player-preferences#11]
Это происходит потому, что на этапе подключения к БД квары содержат только что созданную информацию о данных подключения, а не актуальные данные из конфига.
Таким образом, возникает достаточно серьёзная проблема: целую карту после перезапуска сервера подключение к БД будет отсутствовать

**Comment by ArKaNeMaN** [comment]
Не лучше ли будет сложить креды от БД в какой-нибудь ini/json/* файлик?
